#!/bin/bash

channelsfile=/path/to/your/favorites/channels 
clientID=yourapikey 

if ping -q -c 1 -W 1 8.8.8.8 &>/dev/null; then

    if [[ -n $1 ]]; then
	echo "Checking if $1 is live ..."
	test=$(curl -s https://api.twitch.tv/kraken/streams/"$1"?client_id=$clientID | jq .stream._id)
	if [[ ! $test == "null" ]]; then
	    exec firefox -new-window https://www.twitch.tv/popout/$1/chat?popout= & mpv https://www.twitch.tv/"$1"
	else
	    echo "$1 doesn't stream right now"
	fi

    else

	list_stream_up=""
	echo "Checking connected streams ..."
	channels=$(cat $channelsfile)
        curl -s 'https://api.twitch.tv/kraken/streams?client_id='$clientID'&channel='$channels >~/.script/twitch/twitchdata.tmp
	numberlive=$(cat ~/.script/twitch/twitchdata.tmp | jq ._total)
	i=0
	while [[ ! $i == $numberlive ]]; do
	    check=$(cat ~/.script/twitch/twitchdata.tmp | jq '.streams['$i'].channel.name')
	    check="${check%\"}"
	    check="${check#\"}"
	    list_stream_up="$list_stream_up$check\n"
	    ((i= $i + 1 ))
	done
	rm ~/.script/twitch/twitchdata.tmp
	stream=$(echo -e $list_stream_up | dmenu -i -p "Which stream do you want to watch?")
	if [[ -n $stream ]];then
	    exec firefox -new-window https://www.twitch.tv/popout/$stream/chat?popout= & mpv https://www.twitch.tv/"$stream"
	else
	    echo "Aborted"
	fi
    fi
else
    echo "No internet connection"  
fi
